<%
  socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
  "/var/run/mysql5/mysqld.sock",
  "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["BOXEN_MYSQL_PORT"] || "3306"
%>

mysql_connection: &mysql_connection
<% if socket %>
  host: localhost
  socket: <%= socket %>
<% else %>
  host: 127.0.0.1
  port: <%= port %>
<% end %>

mysql_settings: &mysql_settings
  adapter:   mysql2
  encoding:  utf8
  reconnect: false
  pool:      5

local_user: &local_user
  <<: *mysql_settings
  <<: *mysql_connection
  username: root
  password:

development: &development
  <<: *local_user
  database: curate
  host:     localhost
  timeout: 5000

test: &test
  <<: *development
  database: curate
ci: &ci
  <<: *test
