development: &development
  username: apitest
  password: apitest
  shoulder: doi:10.5072/FK2
  url: https://ezid.cdlib.org
test: &TEST
  username: apitest
  password: apitest
  shoulder: doi:10.5072/FK2
  url: https://ezid.cdlib.org
