development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://curate-devdb/fedora
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "data.local:#{ENV['TEST_JETTY_PORT'] || 8080}/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://data.local:8080/fedora
cucumber:
  <<: *TEST
