# stores ReCaptcha image server url

development:
  site_key: bamboo_captcha_site_key
  secret_key: bamboo_captcha_secret_key
test:
  site_key: bamboo_captcha_site_key
  secret_key: bamboo_captcha_secret_key
production:
  site_key: bamboo_captcha_site_key
  secret_key: bamboo_captcha_secret_key
