# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: http://curate-devdb.uc.edu/solr/repository
test: &TEST
  url: <%= "http://data.local:#{ENV['TEST_JETTY_PORT'] || 8080}/solr/test" %>
cucumber:
  <<: *TEST
ci:
  <<: *TEST
production:
  url: http://data.local:8080/bl_solr/core0 
